# Generated by Django 5.0.4 on 2024-05-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneproducts',
            old_name='phone_model',
            new_name='model',
        ),
        migrations.AddField(
            model_name='phoneproducts',
            name='slug',
            field=models.SlugField(default=123, unique=True),
            preserve_default=False,
        ),
    ]
