# Generated by Django 5.0.4 on 2024-05-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_phone_model_phoneproducts_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneproducts',
            name='color',
        ),
        migrations.AddField(
            model_name='phoneproducts',
            name='colors',
            field=models.ManyToManyField(to='products.productcolors'),
        ),
        migrations.AlterField(
            model_name='phoneproducts',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
