# Generated by Django 5.0.4 on 2024-05-22 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_price'),
        ('products', '0003_remove_phoneproducts_color_phoneproducts_colors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productAttributs',
            new_name='ProductAttribut',
        ),
        migrations.RenameModel(
            old_name='productBrands',
            new_name='ProductBrand',
        ),
        migrations.RenameModel(
            old_name='productColors',
            new_name='ProductColor',
        ),
        migrations.RenameModel(
            old_name='productOptions',
            new_name='ProductOption',
        ),
        migrations.RenameModel(
            old_name='productStorages',
            new_name='ProductStorage',
        ),
        migrations.RenameModel(
            old_name='phoneProducts',
            new_name='Product',
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
