# Generated by Django 5.0.4 on 2024-05-22 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_productattributs_productattribut_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribut',
            new_name='ProductAttribute',
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product'),
        ),
    ]
